version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    environment:      #https://linuxtut.com/en/c8f9df8defc937e185ee/
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books            
    ports:
      - "3306:3306"
#    volumes:
#      - spring_data:/var/lib/mysql

#volumes:
#  spring_data: